"""
Excel Service — pure data-export utility.

Converts agent state data into a multi-sheet Excel workbook.
No LangGraph dependency — called directly from streamlit_app.py
after the graph completes if export_excel intent is present.
"""

import os
import pandas as pd
from datetime import datetime


def generate_excel_report(result: dict) -> str | None:
    """
    Build a multi-sheet Excel report from the graph result state.

    Args:
        result: The output dict from graph.invoke()

    Returns:
        Absolute path to the generated .xlsx file, or None if the caller
        didn't request an export or access was denied.
    """
    intents = result.get("intents", [])
    if "export_excel" not in intents or not result.get("access_granted"):
        return None

    employee_data = result.get("employee_data")
    department_stats = result.get("department_stats")
    org_data = result.get("organization_data")
    team_data = result.get("team_data")
    promotion_candidates = result.get("promotion_candidates")
    current_user = result.get("current_user", {})

    export_dir = "exports"
    os.makedirs(export_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = f"{export_dir}/Report_{timestamp}.xlsx"

    with pd.ExcelWriter(file_path, engine="openpyxl") as writer:

        # Sheet 1: Employee Details
        if employee_data:
            emp_flat = employee_data.copy()
            emp_flat.pop("manager_data", None)
            pd.DataFrame([emp_flat]).to_excel(writer, sheet_name="Employee Details", index=False)

        # Sheet 2: Department Statistics
        if department_stats:
            dept_rows = [department_stats] if isinstance(department_stats, dict) else department_stats
            pd.DataFrame(dept_rows).to_excel(writer, sheet_name="Department Statistics", index=False)

        # Sheet 3: Team Hierarchy
        if team_data and "direct_reports" in team_data:
            df_team = pd.DataFrame(team_data["direct_reports"])
            if not df_team.empty:
                df_team.to_excel(writer, sheet_name="Team Reports", index=False)

        # Sheet 4: Organization Analytics
        if org_data:
            overall = org_data.get("overall_stats") or org_data.get("stats")
            if overall:
                pd.DataFrame([overall]).to_excel(writer, sheet_name="Overall Org Stats", index=False)

            dept_all = org_data.get("department_stats")
            if dept_all:
                pd.DataFrame(dept_all).to_excel(writer, sheet_name="All Dept Stats", index=False)

            heads = org_data.get("heads")
            if heads:
                pd.DataFrame(heads).to_excel(writer, sheet_name="Dept Heads", index=False)

            top_paid = org_data.get("top_paid_employees")
            if top_paid:
                pd.DataFrame(top_paid).to_excel(writer, sheet_name="Top Paid Employees", index=False)

        # Sheet 5: Promotion Analysis
        if promotion_candidates:
            df_promo = pd.DataFrame(promotion_candidates)
            if not df_promo.empty:
                df_promo.to_excel(writer, sheet_name="Promotion Candidates", index=False)

        # Sheet 6: Audit Trail
        pd.DataFrame({
            "Generated By": [current_user.get("name", "Unknown")],
            "Role": [current_user.get("role", "Unknown")],
            "Timestamp": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            "Access Status": [result.get("auth_message", "N/A")],
        }).to_excel(writer, sheet_name="Audit Trail", index=False)

    print(f"[Excel Service] Workbook written → {file_path}")
    return file_path
