import pandas as pd
import os
from datetime import datetime
from typing import Dict, Any
def excel_export_agent(state):
    intents = state.get("intents", [])
    if "export_excel" not in intents or not state.get("access_granted"):
        return state

    employee_data = state.get("employee_data")
    department_stats = state.get("department_stats")
    org_data = state.get("organization_data")
    team_data = state.get("team_data")
    promotion_candidates = state.get("promotion_candidates")
    current_user = state.get("current_user", {})
    
    # Ensure export directory exists
    export_dir = "exports"
    if not os.path.exists(export_dir):
        os.makedirs(export_dir)
        
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = f"{export_dir}/Report_{timestamp}.xlsx"

    print("\n========================")
    print("ORG DATA")
    print(org_data)
    print("========================\n")
    
    with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
        # Sheet 1: Employee Details
        if employee_data:
            # Flatten manager data for cleaner excel
            emp_flat = employee_data.copy()
            if "manager_data" in emp_flat:
                 del emp_flat["manager_data"]
            df_emp = pd.DataFrame([emp_flat])
            df_emp.to_excel(writer, sheet_name='Employee Details', index=False)
            
        # Sheet 2: Department Statistics
        if department_stats:
            dept_to_df = [department_stats] if isinstance(department_stats, dict) else department_stats
            df_dept = pd.DataFrame(dept_to_df)
            df_dept.to_excel(writer, sheet_name='Department Statistics', index=False)

        # Sheet 3: Team Hierarchy
        if team_data and "direct_reports" in team_data:
            df_team = pd.DataFrame(team_data["direct_reports"])
            if not df_team.empty:
                df_team.to_excel(writer, sheet_name='Team Reports', index=False)

        # Sheet 4: Organization Analytics
        if org_data:
            # Defensive check for overall stats
            overall = org_data.get("overall_stats") or org_data.get("stats")
            if overall:
                pd.DataFrame([overall]).to_excel(writer, sheet_name='Overall Org Stats', index=False)
            
            dept_all = org_data.get("department_stats")
            if dept_all:
                pd.DataFrame(dept_all).to_excel(writer, sheet_name='All Dept Stats', index=False)
            
            heads = org_data.get("heads")
            if heads:
                pd.DataFrame(heads).to_excel(writer, sheet_name='Dept Heads', index=False)
            
            top_paid = org_data.get("top_paid_employees")
            if top_paid:
                pd.DataFrame(top_paid).to_excel(writer, sheet_name='Top Paid Employees', index=False)

        # Sheet 5: Promotion Analysis
        if promotion_candidates:
            df_promo = pd.DataFrame(promotion_candidates)
            if not df_promo.empty:
                df_promo.to_excel(writer, sheet_name='Promotion Candidates', index=False)

        # Sheet 6: Access Metadata
        metadata = {
            "Generated By": [current_user.get("name", "Unknown")],
            "Role": [current_user.get("role", "Unknown")],
            "Timestamp": [datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            "Access Status": [state.get("auth_message", "N/A")]
        }
        pd.DataFrame(metadata).to_excel(writer, sheet_name='Audit Trail', index=False)

    trace = state.get("trace", [])
    trace.append(f"Excel Export Agent → Exported comprehensive workbook to {file_path}")

    return {
        **state,
        "analysis": f"✅ Excel report generated successfully!\n\nFile: {file_path}",
        "excel_path": file_path,
        "trace": trace
    }